### ISSUE TITLE
jupyter vs jupyter-notebook

### ISSUE THREAD

**Issue by dbkeitel** [Asterics2020-Obelics/School2017#11]
I'm on Debian Stretch. When I try to do "jupyter notebook" as recommended in the readme, this fails, e.g.
```
jupyter astropy/astropy_hands_on.ipynb 
jupyter: 'astropy/astropy_hands_on.ipynb' is not a Jupyter command
```
Opening the same ipynb with "jupyter-notebook" as the executable works fine.
Both executables come from my system install, with some relevant package versions being jupyter-client 4.4.0-2, jupyter-core 4.2.1-1 and jupyter-notebook 4.2.3-4

Is this an ok situation and I should just use jupyter-notebook, or does it indicate some deeper install/config issues and I should e.g. reinstall something through anaconda instead of from Debian packages, or check my PATH, ...? According to https://github.com/jupyter/notebook/issues/448 this symptom can have many possible sources, but if it is not serious, then I'm happy with using the alternate command.

**Comment by nicolaschotard** [comment]
@dbkeitel You can either run 

    jupyter notebook

and then select in your browser the notebook you would like to run. Or directly launch it from command line as you did

    jupyter-notebook yournotebook.ipynb

Both ways are fine.

**Comment by dbkeitel** [comment]
Oh ok, I had assumed that "notebook" in the first version was a placeholder, not verbatim. Thanks for the clarification!
