### ISSUE TITLE
Cannot install pytables package

### ISSUE THREAD

**Issue by tristan0x** [Asterics2020-Obelics/School2017#2]
When executing the `pip install -r requirements.txt` after sourcing the `anaconda_setup.sh` script as specified in the documentation, the command fails with the following output:

```
Collecting pytables (from -r requirements.txt (line 13))
  Could not find a version that satisfies the requirement pytables (from -r requirements.txt (line 13)) (from versions: )
No matching distribution found for pytables (from -r requirements.txt (line 13))
```

**Comment by tamasgal** [comment]
Fixed in https://github.com/Asterics2020-Obelics/School2017/commit/2d379a95cd8109152873df4f470d59b1b4a22eee

**Comment by tamasgal** [comment]
Uh, Tristan, you're fast too 😆

**Comment by Asterics2020-Obelics** [comment]
If you install Python with `anaconda`, you should not execute the `pip install -r requirements.txt` command, as everything should come with `anaconda`. But it might not be clear enough in the doc...

**Comment by tristan0x** [comment]
@Asterics2020-Obelics IMHO the documentation is clear enough if you take the time to read it. When I tested the installation procedure on several Linux distros, I savagely copied/pasted the commands instead of reading instructions carefully.
