### ISSUE TITLE
Python 2 vs python 3

### ISSUE THREAD

**Issue by jmarclegoff** [Asterics2020-Obelics/School2017#8]

**Comment by jmarclegoff** [comment]
My collaboration (SDSS) uses python 2.7. 
I suppose it is not possible to use python 2.7 for the school, correct ?
Since there is no backward compatibility and I still need to run codes in 2.7
Is there a way to install Python 3.6 and still having python 2.7
and switching from one to the other in some way ?
thank you very much
Jean-Marc Le Goff

**Comment by nicolaschotard** [comment]
Hello Jean-Marc. The Python install recommendation that we give allows you to install anaconda3 while keeping your system and previous install of Python totally intact (no modification of your PATH or PYTHONPATH). See [here](https://github.com/Asterics2020-Obelics/School2017#python). After installing `anaconda` (in your home directory), use one of the `anaconda_setup` script to activate this install in a given terminal. This will only change your PATH and PYTHONPATH for this terminal, but will not affect other session that you might be running in parallel.

I should mention that I was considering that you were using Linux or Mac.

**Comment by adonath** [comment]
@jmarclegoff Alternatively, in case you already work with Anaconda, you can use conda environments with different versions of Python (see accepted answer [here](https://stackoverflow.com/questions/24405561/how-to-install-2-anacondas-python-2-7-and-3-4-on-mac-os-10-9)).
